### ISSUE TITLE
Remove Scrollbars

### ISSUE THREAD

**Issue by nahtnam** [ludicrousxyz/ctrl-tab#20]
Scrollbars have started to show again (only on Chrome) and won't go away. They are very distracting and would probably look a lot better if they were hidden until the user starts scrolling.

**Comment by nahtnam** [comment]
I'm stumped on this, if anyone else would like to take a crack at it, I would appreciate the help. They were gone for a long time, and then they somehow popped up and refuse to go away regardless of the CSS I put.

**Comment by c-ciobanu** [comment]
I think if you want to hide the scrollbar it's better and more intuitive if you show the scrollbar on hover instead of scrolling.

**Comment by nahtnam** [comment]
Yep, that is what I'm going for, and that is what MacOS does by default. For some reason, now it is working:
![screenshot](https://i.imgur.com/GE1WV5W.png)

I am trying to see if there is a cross platform solution that will work.

**Comment by nahtnam** [comment]
This looks like a good solution: https://stackoverflow.com/questions/8631799/make-scrollbars-only-visible-when-a-div-is-hovered-over

Will implement soon. WDYT?

**Comment by nahtnam** [comment]
I implemented it in https://github.com/ludicrousxyz/ctrl-tab/pull/26, just need to find time to do some testing before I deploy it.
